### ISSUE TITLE
Návrh na překlad u plavčíka

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-6-CZ-translation-#5]
![image](https://github.com/user-attachments/assets/8ce9bc7a-7e90-413f-8fcf-3f424e91ddfb)

Tohle (viz obrázek) říká plavčík Larrymu, když mu Larry ukáže nenafouknutého nafukovacího bobra. Větu "Beside, it tires me." máme sice správně přeloženou jako "Navíc mě to unavuje.", ale říkám si, jestli to není nápověda. Larry toho bobra musí totiž nafouknout vzduchem z pneumaticky (tire) v kuchyni. Čili třeba: "Navíc z nafukování vždycky dostanu pneumonii."

Dávám to sem, abych zjistil cizí názor. Nepřemýšlím už zbytečně moc složitě? :-D

**Comment by miracleflame** [comment]
To je výborný postreh, myslím, že máš pravdu a s tou pneumoniou by to šlo podľa mňa.

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/06e326a7-7d23-43a1-8569-2ed1f6570120)
Změněno.
