### ISSUE TITLE
Nevypisující se text v závorce (ozvěna ve sprše)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-6-CZ-translation-#6]
![image](https://github.com/user-attachments/assets/778d1391-27b3-4b22-989a-b7b589c52f53)

Na tomhle místě (soubor 350.cs6/msg) se má vypisovat ještě text v závorce _(13... 13...)_, což má být ozvěna ve sprše. U "sousedících" hlášek se to vypisuje správně:
_Teď na pálku jde (jde... jde...)
Larry Laffer! (hned si naser... naser...)_

Možná to souvisí s tím, že některé závorky, které v souborech jsou, se nevypisují - tam, kde se popisuje nálada, nebo zvuk. Například _(S OZVĚNOU A HLUBOKÝM HLASEM) Teď na pálku jde (jde... jde...)_

**Comment by miracleflame** [comment]
To je ale donebavolajúca kravina, aby sa v sprche ozýval zvuk s oneskorením, akoby cestoval stovky metrov. :D
Každopádne zamýšlam sa a jediné, čo mi napadá v tejto súvisloti je prepísať to slovne... Možno je ten komentovací systém naprogramovaný tak, aby sa kapitálky a čísla v zátvorke nevypisovali.

**Comment by PetrCejpek** [comment]
To máš vlastně pravdu, že je to nefyzikální kravina. :-D To by ta sprcha musela mít alespoň 100 m. :-D Každopádně, změnil jsem to podle tvého doporučení a pomohlo to:
![image](https://github.com/user-attachments/assets/7245f6eb-9814-4cf8-91bf-e60c75c42c90)
